#!/bin/bash

# Usage: varycachesize 256 8192 
# for powers of two from 256 to 8192 inclusive

for ((x=$1; x <= $2 ; x *= 2))
do
  echo -n "D1_cache_size" $x " dl1.miss_rate "
  export SSFLAGS="-cache:dl1 dl1:$x:32:1:l"
  ./run-wattch \
     2>&1 | grep dl1.miss_rate | awk '{print $2;}'
done
